- name: Install HAProxy
  ansible.builtin.yum:
    name: haproxy
    state: present

- name: Configure HAProxy
  ansible.builtin.template:
    src: ha_proxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: restart haproxy

- name: Enable and start HAProxy service
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: started